### TEST GET / WEBSITE
GET http://localhost:8585

### TEST GET /dashboard WEBSITE
GET http://localhost:8585/dashboard

### DATA ENDPOINT
GET http://localhost:8585/api/data

### DATA ENDPOINT FOR ADDING A USER
POST http://localhost:8585/api/data
Content-Type: application/json

{
    "name":"Voldamort"
}

### DELETE ENDPOINT
DELETE http://localhost:8585/api/data